POST http://localhost:3005/register HTTP/1.1
Content-Type: application/json

{
    "userName" : "raavan",
    "password" : "123456"
}

###

POST http://localhost:3005/login HTTP/1.1
content-type: application/json

{
    "userName" : "raavan",
    "password" : "123456"
}

###

GET https://opentdb.com/api.php?amount=10&category=9&difficulty=easy&type=multiple HTTP/1.1